git submodule add https://github.com/jlanzarotta/bufexplorer pack/plugins/start/bufexplorer
git submodule add https://github.com/majutsushi/tagbar pack/plugins/start/tagbar
git submodule add https://github.com/tpope/vim-commentary pack/plugins/start/vim-commentary
git submodule add https://github.com/tpope/vim-surround pack/plugins/start/vim-surround
git submodule add https://github.com/tpope/vim-unimpaired pack/plugins/start/vim-unimpaired
git submodule add https://github.com/dzeban/vim-log-syntax pack/plugins/start/vim-log-syntax
git submodule add https://github.com/tpope/vim-sensible pack/plugins/start/vim-sensible
git submodule add https://github.com/tpope/vim-fugitive pack/plugins/start/vim-fugitive
git submodule add https://github.com/tpope/vim-repeat pack/plugins/start/vim-repeat
git submodule add https://github.com/skywind3000/asyncrun.vim.git pack/plugins/start/asyncrun
git submodule add https://github.com/nvie/vim-flake8.git pack/plugins/start/vim-flake8
git submodule add https://github.com/tpope/vim-abolish.git pack/plugins/start/vim-abolish
git submodule add https://github.com/madox2/vim-ai.git pack/plugins/start/vim-ai
